name: tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: YosysHQ setup
      uses: YosysHQ/setup-oss-cad-suite@v2
      with:
        version: '2023-11-20'
        python-override: true
      
    - name: RISC-V GNU setup
      uses: gregdavill/setup-riscv-gnu-toolchain@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: configure python
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade setuptools
        python3 -m pip install --upgrade wheel
        python3 -m pip install Sphinx sphinxcontrib-wavedrom

    - name: Litex sim build
      run: |
        ./frostyferret_soc.py --sim

    - name: Litex fpga build
      run: |
        ./frostyferret_soc.py --build

    - name: Firmware build
      working-directory: fw/asm_blink
      run: make all blink.cde blink.disasm
        
    - name: cocotb-test
      working-directory: verif/sim
      run: make
    
    - uses: actions/upload-artifact@v3  # upload test results
      if: success() || failure()        # run this step even if previous step failed
      with:
          name: cocotb-results
          path: verif/sim/results.xml
        
    